### PR TITLE
fix: update frame range when write node is selected

### PR DESCRIPTION
**Pull request by diane-hj**
### What was the problem/requirement? (What/Why)
- When write node is selected, incorrect frame range were exported in parameters

### What was the solution? (How)
- When override frame is selected, override the frame
- When write node is selected with limit_range checked (without override), write node's frame applied
- When write node is selected without limit_range checked (without override), project settings frame applied
- When no specific write node is selected, project settings frame applied

### What is the impact of this change?
- Based on the customers' setting, right frame range is selected as explained above 

### How was this change tested?
- Opened Nuke with the following setting: 
```
Project setting frame: 1-4
Write1 node frame: 1-10
Override when selected with frame: 4
```
Verified the following: 
```
All write nodes, without frame override —> 1 - 4 
All write nodes, with frame override —> 4 
All write nodes, without frame override —> 1 - 4

Write1, with limitRange, without frame override —> 1 - 10 
Write1, with limitRange, with frame override —> 4
Write1, with limitRange, without frame override —> 1- 10 

Write1, without limitRange, without frame override —> 1- 4
Write1, without limitRange, with frame override —> 4 
Write1, without limitRange, without frame override —> 1 - 4 

```
### Did you run the "Job Bundle Output Tests"? If not, why not? If so, paste the test results here.

```

Timestamp: 2024-08-12T14:01:24.012286-07:00
Running job bundle output test: /Users/chaejung/Desktop/submitter/deadline-cloud-for-nuke/job_bundle_output_tests/group-read

group-read
Test succeeded

Timestamp: 2024-08-12T14:01:25.055533-07:00
Running job bundle output test: /Users/chaejung/Desktop/submitter/deadline-cloud-for-nuke/job_bundle_output_tests/noise-saver

noise-saver
Test succeeded

Timestamp: 2024-08-12T14:01:26.720246-07:00
Running job bundle output test: /Users/chaejung/Desktop/submitter/deadline-cloud-for-nuke/job_bundle_output_tests/multi-load-save

multi-load-save
Test succeeded

Timestamp: 2024-08-12T14:01:27.757395-07:00
Running job bundle output test: /Users/chaejung/Desktop/submitter/deadline-cloud-for-nuke/job_bundle_output_tests/frame

frame
Test succeeded

Timestamp: 2024-08-12T14:01:29.360422-07:00
Running job bundle output test: /Users/chaejung/Desktop/submitter/deadline-cloud-for-nuke/job_bundle_output_tests/ocio

ocio
Test succeeded

Timestamp: 2024-08-12T14:01:30.340508-07:00
Running job bundle output test: /Users/chaejung/Desktop/submitter/deadline-cloud-for-nuke/job_bundle_output_tests/cwd-path

cwd-path
Test succeeded

All tests passed, ran 6 total.
Timestamp: 2024-08-12T14:01:33.469925-07:00

```

### Was this change documented?
I don't think so. 
### Is this a breaking change?
This is a fix. 

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

### CODE REVIEW

**Review by epmog — CHANGES_REQUESTED** [review]
Thanks for the PR!

I believe this is the type of change we need since the write node frame range is bugged, but I think there's an additional section we have to update here that will have the exact same problem: https://github.com/aws-deadline/deadline-cloud-for-nuke/pull/154/files#diff-fb4f3580c4b9cd3e4360d8e095ffc997ebf2a140868124094ddbb8755d3ee51fR155-R157

That section there is ran when the user is specifying a write node (rather than all of them).

**Comment by epmog** [comment]
It probably makes sense to include this as one of the job bundle tests as well to help ensure we don't regress.

The job bundle tests are basically structured in such a way that given a scene file, we can verify the output bundle that gets created. So if we have a write node that has different frames from the project, we are then testing it with the expected bundle matching the write node.

Let me know your thoughts

**Review by epmog — APPROVED** [review]
Thanks for making those changes. LGTM!

**Review by Cherie-Chen — APPROVED** [review]
Looks great! Thank you for adding a through test for this fix!

**Pull request merged**
